apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: cassandra3
  name: cassandra3
spec:
  replicas: 1
  selector:
    name: cassandra3
  template:
    metadata:
      labels:
        name: cassandra3
    spec:
      containers:
        - image: 127.0.0.1:5000/inu/cassandra-kubernetes:3.0
          name: cassandra3
          env:
            - name: PEER_DISCOVERY_SERVICE
              value: cassandra3-peers

            # Feel free to change the following:
            - name: CASSANDRA_CLUSTER_NAME
              value: Cassandra
            - name: CASSANDRA_DC
              value: datacenter1
            - name: CASSANDRA_RACK
              value: Kubernetes Cluster
            - name: CASSANDRA_ENDPOINT_SNITCH
              value: GossipingPropertyFileSnitch
          ports:
            - containerPort: 9042
              name: cql
          volumeMounts:
            - mountPath: /var/lib/cassandra/data
              name: data
      volumes:
        - glusterfs:
            endpoints: glusterfs-cluster
            path: cassandra3
            readOnly: false
          name: data
